server:
  port: 8762
spring:
  application:
    name: nacos-provider
  cloud:
    nacos:
      discovery:
        server-addr: elvis.ziyun56.com:18483
      config:
        server-addr: elvis.ziyun56.com:18483
        file-extension: yaml
        prefix: nacos-provider
    sentinel:
          transport:
            port: 8719
            dashboard: elvis.ziyun56.com:18485
  profiles:
    active: dev